/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Result, } from "./helpers/IResult";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface SearchBox {
    }
    interface SearchResult {
        "albumName": string;
        "artistName": string;
        "thumbnailURL": string;
    }
    interface SearchResults {
        "resultsArray": Result[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {
    }
    var HTMLSearchBoxElement: {
        prototype: HTMLSearchBoxElement;
        new (): HTMLSearchBoxElement;
    };
    interface HTMLSearchResultElement extends Components.SearchResult, HTMLStencilElement {
    }
    var HTMLSearchResultElement: {
        prototype: HTMLSearchResultElement;
        new (): HTMLSearchResultElement;
    };
    interface HTMLSearchResultsElement extends Components.SearchResults, HTMLStencilElement {
    }
    var HTMLSearchResultsElement: {
        prototype: HTMLSearchResultsElement;
        new (): HTMLSearchResultsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "search-box": HTMLSearchBoxElement;
        "search-result": HTMLSearchResultElement;
        "search-results": HTMLSearchResultsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface SearchBox {
        "onFlowUp"?: (event: CustomEvent<string>) => void;
    }
    interface SearchResult {
        "albumName"?: string;
        "artistName"?: string;
        "thumbnailURL"?: string;
    }
    interface SearchResults {
        "resultsArray"?: Result[];
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "search-box": SearchBox;
        "search-result": SearchResult;
        "search-results": SearchResults;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "search-box": LocalJSX.SearchBox & JSXBase.HTMLAttributes<HTMLSearchBoxElement>;
            "search-result": LocalJSX.SearchResult & JSXBase.HTMLAttributes<HTMLSearchResultElement>;
            "search-results": LocalJSX.SearchResults & JSXBase.HTMLAttributes<HTMLSearchResultsElement>;
        }
    }
}
